# Sabe 'quando rodar', 'como rodar', 'onde publicar dados', 'como receber entradas'. 'loop', 'clock', 'interfaces'.
# NÃ£o sabe como a planta funciona internamente.

[package]
name = "te_service"
version = "0.1.0"
edition = "2021"

[dependencies]
te_core = { path = "../core" }